# Generated by Django 3.2.8 on 2022-04-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
